---
- name: PPA (Personal Package Archive) 取得
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
  tags:
    - nodejs

- name: インストール
  apt:
    name={{ item }}
    state=present
  with_items:
    - nodejs
  tags:
    - nodejs

- name: npmパッケージのインストール
  npm:
    name={{ item }}
    global=yes
    state=present
  with_items:
    - browserify
  tags:
    - nodejs
